language: node_js

node_js: 
  - "8"

before_install:
  - "npm install"
  - "export NODE_ENV=production"

script:
  - "npm run test"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8